title = "Laurence A. F. Park"
#baseURL = "https://example.com"
#languageCode = "en-us"
locale = "en-us"
#theme = "ananke"

MetaDataFormat = "yaml"
DefaultContentLanguage = "en"
SectionPagesMenu = "main"
pagination.pagerSize = 10
googleAnalytics = ""
enableRobotsTXT = true

#baseURL = "https://staff.cdms.westernsydney.edu.au/~lapark/v2/"
baseURL = "https://lapark.github.io/"
relativeURLs = true
#canonifyURLs = true
canonifyURLs = false

Copyright = "This page, its contents and style, are the responsibility of the author and do not necessarily represent the views, policies or opinions of Western Sydney University. The header image Memorial to Folly is unofficial Fan Content permitted under the Fan Content Policy. Not approved/endorsed by Wizards. Portions of the materials used are property of Wizards of the Coast. ©Wizards of the Coast LLC. All other content &copy; Laurence Park"

[module]
#https://www.thenewdynamic.com/article/hugo-modules-everything-from-imports-to-create/
[[module.imports]]
disable = false
ignoreConfig = false
ignoreImports = false
path = 'github.com/theNewDynamic/gohugo-theme-ananke/v2'

ximage = "https://magic.wizards.com/en/articles/archive/card-preview/memorializing-dominaria-2018-04-04"
[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[frontmatter]
featured_image = "/images/mtf.jpg"

[cascade]
[cascade.params]
featured_image = "/images/mtf.jpg"

[caches]
  [caches.images]
    dir = ':cacheDir/images'

