featured_image = "/images/mtf.jpg"
ximage = "https://magic.wizards.com/en/articles/archive/card-preview/memorializing-dominaria-2018-04-04"

# choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
background_color_class = "bg-black"
#featured_image = "/images/gohugo-default-sample-hero-image.jpg"
recent_posts_number = 2

favicon = ""
#:description = "Academic news and research from the office of Laurence"
facebook = ""
twitter = "https://twitter.com/lafpark"
instagram = ""
youtube = ""
github = ""
gitlab = ""
linkedin = ""
mastodon = ""
slack = ""


[ananke]
show_recent_posts = true # show recent posts on the homepage
featured_image = "/images/mtf.jpg"

[ananke.social]
icon_path = "ananke/socials/%s.svg"

[ananke.social.follow]
new_window_icon = false # show a little "opens in new window" icon next to the link
# add networks to this list in your local config to enable them, remove them to disable them.
networks = [
#   "facebook",
   "bluesky"
#   "linkedin"
 ]

[ananke.social.share]
icons = true # show icons for each share link
sharetext = true # show the share text
# add networks to this list in your local config to enable them, remove them to disable them.
networks = [
#   "email",
   "facebook",
   "bluesky",
   "linkedin"
]


# social media network setups
[ananke.social.networks.bluesky]
slug = "bluesky"
label = "Bluesky"
color = "#1185fe"
profile = "https://bsky.app/profile/lapark.mldm.org"
icon = "bluesky" # font awesome brand icon name
link = "https://bsky.app/intent/compose"
[ananke.social.networks.bluesky.particles]
text = "permalink"

